# Generated by Django 5.0 on 2024-01-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.BigIntegerField(choices=[(3, 'Shoes'), (1, 'Clothes'), (2, 'Mobile')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdetails',
            field=models.CharField(max_length=100, verbose_name='product details'),
        ),
    ]
