# Generated by Django 5.0 on 2024-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.BigIntegerField(choices=[(3, 'Samsung'), (1, 'Iphone'), (2, 'Oneplus')], verbose_name='category'),
        ),
    ]
